### ISSUE TITLE
how to uninstall this mod

### ISSUE THREAD

**Issue by shey-kail** [xuwd1/mechrevo-wujie14-kmod#1]
like the title

**Comment by xuwd1** [comment]
> like the title

The way to uninstall/remove the kernel mod may vary depending on how you have installed it. If you are an arch user and installed this kmod via the AUR package, then you could remove it with something like `yay -Rus mechrevo-wujie14-dkms`. However if you installed it manually with dkms things can get a little complicated... You basically need to reverse everything happened during installation. I will update the README file in the near future to give a hopefully detailed uninstalling guide.

**Comment by xuwd1** [comment]
> like the title

Uninstalling instructions added in the README, please check it.

**Comment by shey-kail** [comment]
> > like the title
> 
> Uninstalling instructions added in README, please check it.

thank you very much
