### ISSUE TITLE
Any chance to add support for 14X?

### ISSUE THREAD

**Issue by liolok** [xuwd1/mechrevo-wujie14-kmod#3]
Just tested on Arch Linux, 14XA (White version of 14X), used PKGBUILD from AUR upgraded to 1.0 tag. Kernel module loaded and powerprofilesctl still shows amd_pstate, not platform_profile.

**Comment by xuwd1** [comment]
Hi.
Currently I'm pretty sure this module would not work for any model other than IP3 ARN39x series. Thus it is currently impossible for this kernel module to work on 14X. 
However, I'm willing to see if I could help making one for 14X if you could provide an ACPI dump following the below:
```bash

# make sure that acpi utilities are installed
sudo pacman -S acpica

# make dump


```

**Comment by liolok** [comment]
[wujie14X_acpi.txt](https://github.com/user-attachments/files/17357826/wujie14X_acpi.txt)

Huge thanks anyway!

**Comment by xuwd1** [comment]
Hi,

Quite unfortunately, I came to a conclusion that 14X is the kind of laptop that I do need an actual machine to possibly develop a kernel module for. The ACPI table indeed seems to have implemented some kind of interface for the control center software to use on Windows, however the ad-hoc variable naming conventions and the lack of comments really prevents me from going any further. So I’m afraid that currently it is out of my reach to make any help.

However I do have several advices:
1. As you have seen, recent AMD CPU scaling driver is actually already taking over the platform_profile interface. Even if you cannot control the power limit settings directly, you could select the appropriate platform profile to let the scaling driver help you save power/increase performance. This recent scaling driver performs quite well based on my experience.
2. I thought that particularly for the 14X model, there should be a led light near the power button indicating the current power mode? I think if plus the fn+x key stroke is hardware handled then it should be good?

Some other notes:
I do have noticed that the price of 14X/15X is quite affordable recently. However I think I would not purchase any other laptop until strix halo APUs come out. I’m sorry about this and I’m closing this issue now.

Best regards

**Comment by w568w** [comment]
I'm capturing ACPI call logs on the 14XA to determine which calls correspond to certain functions. My reverse engineering suggests that WMI isn't directly involved in the 14XA's power mode switching. 

Please see [my notes](https://gist.github.com/w568w/b2fc5f9d1f4dff13efe751abec27b396) for more details.

**Comment by w568w** [comment]
**Update:** I happened to check `GCUService.exe`, the main service process for the control center, and found that it's written in C# .NET and **not obfuscated at all**!

All that dark settings—CPU, GPU overclocking, battery tweaks, "China mode", you name it—seem now out in the open in Plain and Clear Code (TM).

If you're interested, check out my updated notes above. I've done a little digging and learned all the details about the ACPI Platform Profile.
